name: simplecalendar
description: A new perfect simple calendar


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  table_calendar: ^3.0.9


  cupertino_icons: ^1.0.5

dependency_overrides:
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0


  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_icons:
  image_path: 'assets/icons/icon.png'
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
